/**
 * Shared route type generation utility.
 *
 * Generates TypeScript types from routes.json metadata for type-safe routing.
 * Used by the main litestar plugin and framework integrations (Astro, Nuxt, SvelteKit).
 *
 * @module
 */

import * as fs from "node:fs"
import * as path from "node:path"

/**
 * Options for emitRouteTypes.
 */
export interface EmitRouteTypesOptions {
  /**
   * Whether to register route() on window for global access.
   * Only used by the main plugin.
   * @default false
   */
  globalRoute?: boolean

  /**
   * Whether to declare global `var routes` and `var serverRoutes`.
   * Used by framework integrations for SSR compatibility.
   * @default false
   */
  declareGlobalVars?: boolean
}

/**
 * Route metadata from routes.json.
 */
interface RouteData {
  uri: string
  parameters?: string[]
  parameterTypes?: Record<string, string>
}

/**
 * Generate TypeScript route types from routes.json metadata.
 *
 * Creates a routes.ts file with:
 * - routesMeta: full route metadata
 * - routes: name -> uri map
 * - serverRoutes: alias of routes
 * - route(): type-safe URL generator
 * - hasRoute(): type guard
 * - CSRF helpers re-exported from litestar-vite-plugin/helpers
 *
 * @param routesPath - Path to routes.json file
 * @param outputDir - Output directory for routes.ts
 * @param options - Generation options
 */
export async function emitRouteTypes(routesPath: string, outputDir: string, options: EmitRouteTypesOptions = {}): Promise<void> {
  const { globalRoute = false, declareGlobalVars = false } = options

  const contents = await fs.promises.readFile(routesPath, "utf-8")
  const json = JSON.parse(contents)

  const outDir = path.resolve(process.cwd(), outputDir)
  await fs.promises.mkdir(outDir, { recursive: true })
  const outFile = path.join(outDir, "routes.ts")

  const banner = `// AUTO-GENERATED by litestar-vite. Do not edit.
/* eslint-disable */

`

  // Extract just the routes object from the full metadata
  const routesData: Record<string, RouteData> = json.routes || json

  // Build route name union type and route map
  const routeNames = Object.keys(routesData)
  const routeNameType = routeNames.length > 0 ? routeNames.map((n) => `"${n}"`).join(" | ") : "never"

  // Build parameter types for each route
  const routeParamTypes: string[] = []
  for (const [name, data] of Object.entries(routesData)) {
    if (data.parameters && data.parameters.length > 0) {
      const params = data.parameters.map((p) => `${p}: string | number`).join("; ")
      routeParamTypes.push(`  "${name}": { ${params} }`)
    } else {
      routeParamTypes.push(`  "${name}": Record<string, never>`)
    }
  }

  // Build global declarations section
  let globalDeclarations = `declare global {
  interface Window {
    /**
     * Fully-typed route metadata injected by Litestar.
     */
    __LITESTAR_ROUTES__?: typeof routesMeta
    /**
     * Simple route map (name -> uri) for legacy consumers.
     */
    routes?: ${declareGlobalVars ? "typeof routes" : "Record<string, string>"}
    serverRoutes?: ${declareGlobalVars ? "typeof serverRoutes" : "Record<string, string>"}`

  if (globalRoute) {
    globalDeclarations += `
    /**
     * Global route helper (available when globalRoute=true in TypeGenConfig).
     * @see route
     */
    route?: typeof route`
  }

  globalDeclarations += `
  }`

  if (declareGlobalVars) {
    globalDeclarations += `
  // eslint-disable-next-line no-var
  var routes: typeof routes | undefined
  var serverRoutes: typeof serverRoutes | undefined`
  }

  globalDeclarations += `
}`

  // Build global route registration (main plugin only)
  const globalRouteRegistration = globalRoute
    ? `

// Register route() globally on window for Laravel/Ziggy-style usage
if (typeof window !== "undefined") {
  window.route = route
}
`
    : ""

  const body = `/**
 * AUTO-GENERATED by litestar-vite.
 *
 * Exports:
 * - routesMeta: full route metadata
 * - routes: name -> uri map
 * - serverRoutes: alias of routes for clarity in apps
 * - route(): type-safe URL generator
 * - hasRoute(): type guard
 * - csrf helpers re-exported from litestar-vite-plugin/helpers
 *
 * @see https://litestar-vite.litestar.dev/
 */
export const routesMeta = ${JSON.stringify(json, null, 2)} as const

/**
 * Route name to URI mapping.
 */
export const routes = ${JSON.stringify(Object.fromEntries(Object.entries(routesData).map(([name, data]) => [name, data.uri])), null, 2)} as const

/**
 * Alias for server-injected route map (more descriptive for consumers).
 */
export const serverRoutes = routes

/**
 * All available route names.
 */
export type RouteName = ${routeNameType}

/**
 * Parameter types for each route.
 */
export interface RouteParams {
${routeParamTypes.join("\n")}
}

/**
 * Generate a URL for a named route with type-safe parameters.
 *
 * @param name - The route name
 * @param params - Route parameters (required if route has path parameters)
 * @returns The generated URL
 *
 * @example
 * \`\`\`ts
 * import { route } from '@/generated/routes'
 *
 * // Route without parameters
 * route('home')  // "/"
 *
 * // Route with parameters
 * route('user:detail', { user_id: 123 })  // "/users/123"
 * \`\`\`
 */
export function route<T extends RouteName>(
  name: T,
  ...args: RouteParams[T] extends Record<string, never> ? [] : [params: RouteParams[T]]
): string {
  let uri = routes[name] as string
  const params = args[0] as Record<string, string | number> | undefined

  if (params) {
    for (const [key, value] of Object.entries(params)) {
      // Handle both {param} and {param:type} syntax
      uri = uri.replace(new RegExp(\`\\\\{\${key}(?::[^}]+)?\\\\}\`, "g"), String(value))
    }
  }

  return uri
}

/**
 * Check if a route name exists.
 */
export function hasRoute(name: string): name is RouteName {
  return name in routes
}

${globalDeclarations}

// Re-export helper functions from litestar-vite-plugin
// These work with the routes defined above
export { getCsrfToken, csrfHeaders, csrfFetch } from "litestar-vite-plugin/helpers"
${globalRouteRegistration}`

  await fs.promises.writeFile(outFile, `${banner}${body}`, "utf-8")
}
