// This file is auto-generated by TanStack Router plugin
// Run `npm run dev` or `litestar assets generate-types` to regenerate

import { createRootRoute } from "@tanstack/react-router"

// Placeholder route tree - will be regenerated by @tanstack/router-plugin
export const routeTree = createRootRoute()
