"""Tests for HTML transformation utilities."""

from litestar_vite.html_transform import (
    _escape_attr,
    _escape_script,
    inject_body_content,
    inject_head_script,
    inject_json_script,
    set_data_attribute,
)


def test_inject_head_script_basic() -> None:
    """Test basic script injection into head."""
    html = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Test</title>
    </head>
    <body>
        <div id="app"></div>
    </body>
    </html>
    """
    script = "console.log('test');"
    result = inject_head_script(html, script)

    assert "<script>console.log('test');</script>" in result
    assert result.index("</head>") > result.index("<script>console.log('test');</script>")


def test_inject_head_script_with_escape() -> None:
    """Test script injection with escaping.</test>"""
    html = "<html><head></head><body></body></html>"
    script = "const x = '</script>';"
    result = inject_head_script(html, script, escape=True)

    # Should escape the closing script tag
    assert r"<\/script>" in result
    assert "</script></script>" not in result


def test_inject_head_script_no_escape() -> None:
    """Test script injection without escaping."""
    html = "<html><head></head><body></body></html>"
    script = "const x = 1;"
    result = inject_head_script(html, script, escape=False)

    assert "<script>const x = 1;</script>" in result


def test_inject_head_script_case_insensitive() -> None:
    """Test script injection with different case head tags."""
    html = "<HTML><HEAD></HEAD><BODY></BODY></HTML>"
    script = "console.log('test');"
    result = inject_head_script(html, script)

    assert "<script>console.log('test');</script>" in result


def test_inject_head_script_with_comment() -> None:
    """Test script injection with HTML comments.

    NOTE: The current regex-based implementation will inject before
    the FIRST occurrence of </head>, even if it's in a comment.
    This is a known limitation - for production HTML generated by
    build tools like Vite, comments with closing tags are rare.
    """
    html = """
    <html>
    <head>
        <title>Test</title>
        <!-- </head> this is a comment -->
    </head>
    <body></body>
    </html>
    """
    script = "console.log('test');"
    result = inject_head_script(html, script)

    # The script is injected (though possibly before the comment)
    assert "<script>console.log('test');</script>" in result
    # For real-world use cases, avoid comments with closing tags


def test_inject_head_script_no_head_tag() -> None:
    """Test script injection when no head tag exists."""
    html = "<html><body></body></html>"
    script = "console.log('test');"
    result = inject_head_script(html, script)

    # Should fall back to injecting before </html> or at the end
    assert "<script>console.log('test');</script>" in result


def test_inject_head_script_empty() -> None:
    """Test injecting empty script returns unchanged HTML."""
    html = "<html><head></head><body></body></html>"
    result = inject_head_script(html, "")

    assert result == html


def test_inject_body_content_end() -> None:
    """Test injecting content at the end of body."""
    html = "<html><head></head><body><div>existing</div></body></html>"
    content = '<div id="portal"></div>'
    result = inject_body_content(html, content, position="end")

    assert '<div id="portal"></div>' in result
    assert result.index("</body>") > result.index('<div id="portal"></div>')


def test_inject_body_content_start() -> None:
    """Test injecting content at the start of body."""
    html = "<html><head></head><body><div>existing</div></body></html>"
    content = '<div id="top"></div>'
    result = inject_body_content(html, content, position="start")

    assert '<div id="top"></div>' in result
    assert result.index('<div id="top"></div>') < result.index("<div>existing</div>")


def test_inject_body_content_case_insensitive() -> None:
    """Test body content injection is case-insensitive."""
    html = "<HTML><HEAD></HEAD><BODY></BODY></HTML>"
    content = '<div id="test"></div>'
    result = inject_body_content(html, content, position="end")

    assert '<div id="test"></div>' in result


def test_inject_body_content_empty() -> None:
    """Test injecting empty content returns unchanged HTML."""
    html = "<html><head></head><body></body></html>"
    result = inject_body_content(html, "", position="end")

    assert result == html


def test_set_data_attribute_id_selector() -> None:
    """Test setting data attribute with ID selector."""
    html = '<html><body><div id="app">content</div></body></html>'
    result = set_data_attribute(html, "#app", "data-page", '{"foo":"bar"}')

    assert 'data-page="' in result
    assert "&quot;" in result  # JSON should be escaped


def test_set_data_attribute_element_selector() -> None:
    """Test setting data attribute with element selector."""
    html = "<html><body><div>content</div></body></html>"
    result = set_data_attribute(html, "div", "data-test", "value")

    assert 'data-test="value"' in result


def test_set_data_attribute_replace_existing() -> None:
    """Test replacing an existing data attribute."""
    html = '<html><body><div id="app" data-page="old">content</div></body></html>'
    result = set_data_attribute(html, "#app", "data-page", "new")

    assert 'data-page="new"' in result
    assert 'data-page="old"' not in result


def test_set_data_attribute_escapes_value() -> None:
    """Test that attribute values are properly escaped."""
    html = '<html><body><div id="app"></div></body></html>'
    # Value with characters that need escaping
    value = '<script>alert("xss")</script>'
    result = set_data_attribute(html, "#app", "data-value", value)

    # Should be escaped
    assert "&lt;" in result
    assert "&gt;" in result
    assert "&quot;" in result
    # Should not contain unescaped dangerous characters
    assert '<script>alert("xss")</script>' not in result


def test_set_data_attribute_empty_selector() -> None:
    """Test with empty selector returns unchanged HTML."""
    html = '<html><body><div id="app"></div></body></html>'
    result = set_data_attribute(html, "", "data-test", "value")

    assert result == html


def test_inject_json_script() -> None:
    """Test injecting JSON data as a script."""
    html = "<html><head></head><body></body></html>"
    data = {"routes": {"home": "/", "about": "/about"}, "user": {"id": 1, "name": "Test"}}
    result = inject_json_script(html, "__ROUTES__", data)

    assert "window.__ROUTES__" in result
    assert '{"routes":' in result
    assert "home" in result
    assert "/about" in result


def test_inject_json_script_with_unicode() -> None:
    """Test JSON injection preserves unicode characters."""
    html = "<html><head></head><body></body></html>"
    data = {"message": "Hello 世界 🌍"}
    result = inject_json_script(html, "__DATA__", data)

    assert "window.__DATA__" in result
    # Unicode should be preserved (ensure_ascii=False)
    assert "世界" in result
    assert "🌍" in result


def test_complex_html_transformation() -> None:
    """Test multiple transformations on the same HTML."""
    html = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Test App</title>
    </head>
    <body>
        <div id="app"></div>
    </body>
    </html>
    """

    # Inject routes metadata
    routes = {"home": "/", "users": "/users"}
    html = inject_json_script(html, "__ROUTES__", routes)

    # Inject head script
    html = inject_head_script(html, "console.log('init');")

    # Set data attribute
    html = set_data_attribute(html, "#app", "data-page", '{"component":"Home"}')

    # Inject body content
    html = inject_body_content(html, '<div id="portal"></div>', position="end")

    # Verify all transformations
    assert "window.__ROUTES__" in html
    assert "console.log('init');" in html
    assert "data-page=" in html
    assert '<div id="portal"></div>' in html


def test_malformed_html_handling() -> None:
    """Test handling of malformed HTML.

    Risk mitigation: ensure transformer doesn't break on malformed HTML.
    """
    # HTML with unclosed tags
    html = "<html><head><body><div id='app'>content"
    script = "console.log('test');"

    # Should not raise an exception
    result = inject_head_script(html, script)
    assert script in result


def test_html_with_inline_scripts() -> None:
    """Test that existing inline scripts are preserved."""
    html = """
    <html>
    <head>
        <script>var existing = 1;</script>
    </head>
    <body></body>
    </html>
    """
    script = "var injected = 2;"
    result = inject_head_script(html, script)

    # Both scripts should be present
    assert "var existing = 1;" in result
    assert "var injected = 2;" in result


def test_escape_script_helper() -> None:
    """Test the internal script escaping helper."""
    script = "const html = '</script><script>alert(1)</script>';"
    escaped = _escape_script(script)

    assert r"<\/script>" in escaped
    assert "</script>" not in escaped or escaped.count("</script>") == 0


def test_escape_attr_helper() -> None:
    """Test the internal attribute escaping helper."""
    value = '<script>alert("xss")&test</script>'
    escaped = _escape_attr(value)

    assert "&lt;" in escaped
    assert "&gt;" in escaped
    assert "&quot;" in escaped
    assert "&amp;" in escaped
    assert "<script>" not in escaped
