/**
 * Browser helper for WebSocket routes generated by Litestar's ChannelsPlugin.
 *
 * @example
 * ```ts
 * import { createChannelsStream } from "litestar-vite-plugin/helpers"
 *
 * const stream = createChannelsStream({
 *   basePath: "/ws",
 *   channel: "notifications",
 *   onEvent: (event) => console.log(event),
 * })
 * stream.connect()
 * ```
 *
 * @module
 */

import { createEventStream, type EventStream, type EventStreamConfig, resolveStreamUrl } from "./stream.js"

export interface RealtimeChannelShape {
  address: string
  protocol: "websocket" | "sse" | "channels"
  params: Record<string, string>
  send: unknown
  receive: unknown
}

export type ChannelMap = Record<string, RealtimeChannelShape>

export type ChannelName<TChannels extends ChannelMap = ChannelMap> =
  | (keyof TChannels & string)
  | (() => keyof TChannels & string)

export interface ChannelsStreamOptions<
  TFrame = unknown,
  TParams extends Record<string, string | number> = Record<string, string | number>,
> extends Omit<EventStreamConfig<TFrame, TFrame>, "EventSourceCtor" | "sseEvents" | "transport"> {
  channel: ChannelName
  params?: TParams
  basePath?: string
  transformUrl?: (url: URL) => string | URL
}

/**
 * Create a stream for a WebSocket route generated by ChannelsPlugin.
 *
 * @param options - Channel name, optional path parameters, server route prefix, and stream callbacks.
 * @returns A disposable stream that connects only when `connect()` is called.
 */
export function createChannelsStream<
  TFrame = unknown,
  TParams extends Record<string, string | number> = Record<string, string | number>,
>(options: ChannelsStreamOptions<TFrame, TParams>): EventStream<TFrame> {
  const { basePath = "/", channel, params, transformUrl, ...streamOptions } = options
  return createEventStream<TFrame, TFrame>({
    ...streamOptions,
    buildUrl: () => {
      let channelName = typeof channel === "function" ? channel() : channel
      let resolvedPath: string
      if (params && typeof params === "object") {
        channelName = channelName.replace(/\{([^{}]+)\}/g, (_, key) => {
          const val = params[key]
          return val !== undefined ? encodeURIComponent(String(val)) : `{${key}}`
        })
        const cleanChannel = channelName.startsWith("/") ? channelName.slice(1) : channelName
        resolvedPath = cleanChannel
          .split("/")
          .map((seg) => {
            try {
              return encodeURIComponent(decodeURIComponent(seg))
            } catch {
              return encodeURIComponent(seg)
            }
          })
          .join("/")
      } else {
        resolvedPath = encodeURIComponent(channelName)
      }
      const prefix = basePath.endsWith("/") ? basePath : `${basePath}/`
      const url = new URL(resolveStreamUrl(`${prefix}${resolvedPath}`, "websocket"))
      return transformUrl?.(url) ?? url
    },
    transport: "websocket",
  })
}

export interface TypedChannelOptions<TChannel extends RealtimeChannelShape>
  extends Omit<EventStreamConfig<TChannel["receive"], TChannel["send"]>, "EventSourceCtor" | "sseEvents" | "transport"> {
  params?: TChannel["params"]
  basePath?: string
  transformUrl?: (url: URL) => string | URL
}

/**
 * Create a typed channel factory bound to a generated ChannelMap.
 *
 * @param defaults - Default connection options such as basePath.
 * @returns A client factory with a typed `stream` method.
 */
export function createTypedChannels<TChannels extends ChannelMap>(defaults?: { basePath?: string }): {
  stream<K extends keyof TChannels & string>(
    channel: K,
    options: TypedChannelOptions<TChannels[K]>,
  ): EventStream<TChannels[K]["send"]>
} {
  return {
    stream<K extends keyof TChannels & string>(
      channel: K,
      options: TypedChannelOptions<TChannels[K]>,
    ): EventStream<TChannels[K]["send"]> {
      const basePath = options.basePath ?? defaults?.basePath
      return createChannelsStream({
        ...options,
        basePath,
        channel,
      }) as unknown as EventStream<TChannels[K]["send"]>
    },
  }
}
