/**
 * Browser helper for WebSocket routes generated by Litestar's ChannelsPlugin.
 *
 * @example
 * ```ts
 * import { createChannelsStream } from "litestar-vite-plugin/helpers"
 *
 * const stream = createChannelsStream({
 *   basePath: "/ws",
 *   channel: "notifications",
 *   onEvent: (event) => console.log(event),
 * })
 * stream.connect()
 * ```
 *
 * @module
 */

import { createEventStream, type EventStream, type EventStreamConfig, resolveStreamUrl } from "./stream.js"

export type ChannelName = string | (() => string)

export interface ChannelsStreamOptions<TFrame = unknown> extends Omit<EventStreamConfig<TFrame>, "EventSourceCtor" | "sseEvents" | "transport"> {
  channel: ChannelName
  basePath?: string
  transformUrl?: (url: URL) => string | URL
}

/**
 * Create a stream for a WebSocket route generated by ChannelsPlugin.
 *
 * @param options - Channel name, server route prefix, and stream callbacks.
 * @returns A disposable stream that connects only when `connect()` is called.
 */
export function createChannelsStream<TFrame = unknown>(options: ChannelsStreamOptions<TFrame>): EventStream {
  const { basePath = "/", channel, transformUrl, ...streamOptions } = options
  return createEventStream({
    ...streamOptions,
    buildUrl: () => {
      const channelName = typeof channel === "function" ? channel() : channel
      const prefix = basePath.endsWith("/") ? basePath : `${basePath}/`
      const url = new URL(resolveStreamUrl(`${prefix}${encodeURIComponent(channelName)}`, "websocket"))
      return transformUrl?.(url) ?? url
    },
    transport: "websocket",
  })
}
