/**
 * Browser helper for WebSocket routes generated by Litestar's ChannelsPlugin.
 *
 * @example
 * ```ts
 * import { createChannelsStream } from "litestar-vite-plugin/helpers"
 *
 * const stream = createChannelsStream({
 *   basePath: "/ws",
 *   channel: "notifications",
 *   onEvent: (event) => console.log(event),
 * })
 * stream.connect()
 * ```
 *
 * @module
 */

import { createEventStream, type EventStream, type EventStreamConfig, resolveStreamUrl } from "./stream.js"

export interface RealtimeChannelShape {
  address: string
  protocol: "websocket" | "sse" | "channels"
  params?: Record<string, any>
  send?: unknown
  receive?: unknown
}

export type ChannelMap = Record<string, RealtimeChannelShape>

export type ChannelName<TChannels = ChannelMap> = (keyof TChannels & string) | (() => keyof TChannels & string)

export interface ChannelsStreamOptions<TFrame = unknown, TParams extends Record<string, string | number> = Record<string, string | number>> extends Omit<
  EventStreamConfig<TFrame, TFrame>,
  "EventSourceCtor" | "sseEvents" | "transport"
> {
  channel: ChannelName
  params?: TParams
  basePath?: string
  transformUrl?: (url: URL) => string | URL
}

/**
 * Create a stream for a WebSocket route generated by ChannelsPlugin.
 *
 * @param options - Channel name, optional path parameters, server route prefix, and stream callbacks.
 * @returns A disposable stream that connects only when `connect()` is called.
 */
export function createChannelsStream<TFrame = unknown, TParams extends Record<string, string | number> = Record<string, string | number>>(
  options: ChannelsStreamOptions<TFrame, TParams>,
): EventStream<TFrame> {
  const { basePath = "/", channel, params, transformUrl, ...streamOptions } = options
  return createEventStream<TFrame, TFrame>({
    ...streamOptions,
    buildUrl: () => {
      let channelName = typeof channel === "function" ? channel() : channel
      let resolvedPath: string
      if (params && typeof params === "object") {
        channelName = channelName.replace(/\{([^{}]+)\}/g, (_, key) => {
          const val = params[key]
          return val !== undefined ? encodeURIComponent(String(val)) : `{${key}}`
        })
        const cleanChannel = channelName.startsWith("/") ? channelName.slice(1) : channelName
        resolvedPath = cleanChannel
          .split("/")
          .map((seg) => {
            try {
              return encodeURIComponent(decodeURIComponent(seg))
            } catch {
              return encodeURIComponent(seg)
            }
          })
          .join("/")
      } else {
        resolvedPath = encodeURIComponent(channelName)
      }
      const prefix = basePath.endsWith("/") ? basePath : `${basePath}/`
      const url = new URL(resolveStreamUrl(`${prefix}${resolvedPath}`, "websocket"))
      return transformUrl?.(url) ?? url
    },
    transport: "websocket",
  })
}

export interface ChannelMetadataEntry {
  address: string
  protocol: "websocket" | "sse" | "channels"
}

export interface TypedChannelOptions<TChannel extends RealtimeChannelShape> extends EventStreamConfig<TChannel["receive"], TChannel["send"]> {
  params?: TChannel["params"]
  basePath?: string
  address?: string
  transformUrl?: (url: URL) => string | URL
}

function interpolateAddress(address: string, params?: Record<string, unknown>): string {
  if (!params || typeof params !== "object") {
    return address
  }
  return address.replace(/\{([^{}]+)\}/g, (_, key: string) => {
    const val = params[key]
    return val !== undefined ? encodeURIComponent(String(val)) : `{${key}}`
  })
}

/**
 * Create a typed channel factory bound to a generated ChannelMap.
 *
 * @param defaults - Default connection options such as basePath and optional CHANNEL_METADATA.
 * @returns A client factory with a typed `stream` method supporting WebSocket, ChannelsPlugin, and SSE.
 */
export function createTypedChannels<TChannels extends { [K in keyof TChannels]: RealtimeChannelShape } = ChannelMap>(defaults?: {
  basePath?: string
  metadata?: Partial<Record<keyof TChannels & string, ChannelMetadataEntry>>
}): {
  stream<K extends keyof TChannels & string>(channel: K, options: TypedChannelOptions<TChannels[K]>): EventStream<TChannels[K]["send"]>
} {
  return {
    stream<K extends keyof TChannels & string>(channel: K, options: TypedChannelOptions<TChannels[K]>): EventStream<TChannels[K]["send"]> {
      const meta = defaults?.metadata?.[channel]
      const resolvedProtocol = options.transport ?? (meta?.protocol === "sse" ? "sse" : "websocket")
      const basePath = options.basePath ?? defaults?.basePath
      const targetAddress = options.address ?? meta?.address

      if (resolvedProtocol === "sse" || (targetAddress !== undefined && meta?.protocol !== "channels")) {
        const { params, transformUrl, basePath: _bp, address: _addr, ...streamOptions } = options
        const transport = resolvedProtocol === "sse" ? "sse" : "websocket"
        return createEventStream<TChannels[K]["receive"], TChannels[K]["send"]>({
          ...streamOptions,
          transport,
          buildUrl: () => {
            const rawPath = interpolateAddress(targetAddress ?? String(channel), params as Record<string, unknown> | undefined)
            const endpoint = rawPath.startsWith("/") ? rawPath : `${(basePath ?? "/").replace(/\/$/, "")}/${rawPath}`
            const url = new URL(resolveStreamUrl(endpoint, transport))
            return transformUrl?.(url) ?? url
          },
        })
      }

      return createChannelsStream({
        ...options,
        basePath,
        channel: targetAddress ?? channel,
      }) as unknown as EventStream<TChannels[K]["send"]>
    },
  }
}
