/**
 * Browser helper for routes generated by Litestar Queues EventStreamConfig.
 *
 * @example
 * ```ts
 * import { createQueueEventStream } from "litestar-vite-plugin/helpers"
 *
 * const stream = createQueueEventStream({
 *   scope: "task",
 *   taskId: "01J...",
 *   onEvent: (event) => console.log(event),
 * })
 * stream.connect()
 * ```
 *
 * @module
 */

import { createEventStream, type EventStream, type EventStreamConfig, type EventStreamTransport, resolveStreamUrl } from "./stream.js"

export const QUEUE_SSE_EVENTS = [
  "task.started",
  "task.progress",
  "task.log",
  "task.event",
  "task.completed",
  "task.failed",
  "task.cancelled",
  "task.claim_lost",
  "task.stale_failed",
  "worker.heartbeat",
  "worker.stale_recovery",
] as const

export type QueueStreamValue = string | (() => string)
export type QueueStreamTarget =
  | { scope: "task"; taskId: QueueStreamValue }
  | { scope: "queue"; queue: QueueStreamValue }
  | { scope: "worker"; workerId: QueueStreamValue }
  | { scope: "global" }
  | { scope: "custom"; scopeKey: QueueStreamValue }

export type QueueEventStreamOptions<TFrame = unknown> = EventStreamConfig<TFrame> &
  QueueStreamTarget & {
    basePath?: string
    transformUrl?: (url: URL) => string | URL
  }

function asRecord(value: unknown): Record<string, unknown> | undefined {
  return typeof value === "object" && value !== null ? (value as Record<string, unknown>) : undefined
}

function defaultQueueIsHeartbeat(frame: unknown): boolean {
  return asRecord(frame)?.type === "ping"
}

function defaultQueueGetEventKey(frame: unknown): string | undefined {
  const record = asRecord(frame)
  const key = record?.eventKey ?? record?.id
  return typeof key === "string" ? key : undefined
}

function defaultQueueGetSequence(frame: unknown): { stream: string; value: number } | undefined {
  const record = asRecord(frame)
  const sequence = record?.sequence
  const taskId = record?.taskId
  const attempt = record?.attempt
  if (typeof sequence !== "number" || !Number.isFinite(sequence) || typeof taskId !== "string" || (typeof attempt !== "string" && typeof attempt !== "number")) {
    return undefined
  }
  return { stream: `${taskId}:${attempt}`, value: sequence }
}

function resolveValue(value: QueueStreamValue): string {
  return typeof value === "function" ? value() : value
}

function queueRouteSuffix(target: QueueStreamTarget): string {
  switch (target.scope) {
    case "task":
      return `tasks/${encodeURIComponent(resolveValue(target.taskId))}`
    case "queue":
      return `queues/${encodeURIComponent(resolveValue(target.queue))}`
    case "worker":
      return `workers/${encodeURIComponent(resolveValue(target.workerId))}`
    case "global":
      return "global"
    case "custom":
      return `custom/${encodeURIComponent(resolveValue(target.scopeKey))}`
  }
}

function queueStreamUrl(target: QueueStreamTarget, basePath: string, transport: EventStreamTransport): URL {
  const root = basePath.endsWith("/") ? basePath.slice(0, -1) : basePath
  const transportPath = transport === "sse" ? "sse/" : ""
  return new URL(resolveStreamUrl(`${root}/${transportPath}${queueRouteSuffix(target)}`, transport))
}

/**
 * Create a stream for routes generated by QueuePlugin EventStreamConfig.
 *
 * @param options - Queue target, transport, and stream callbacks.
 * @returns A disposable stream that connects only when `connect()` is called.
 */
export function createQueueEventStream<TFrame = unknown>(options: QueueEventStreamOptions<TFrame>): EventStream {
  const {
    baseDelayMs,
    basePath = "/queues/events",
    dedupWindow,
    EventSourceCtor,
    getEventKey = defaultQueueGetEventKey,
    getSequence = defaultQueueGetSequence,
    isHeartbeat = defaultQueueIsHeartbeat,
    maxDelayMs,
    onEvent,
    onGap,
    onHealthChange,
    onReconnect,
    parseFrame,
    shouldReconnect,
    sseEvents = QUEUE_SSE_EVENTS,
    transformUrl,
    transport = "websocket",
    WebSocketCtor,
  } = options

  return createEventStream({
    baseDelayMs,
    buildUrl: () => {
      const url = queueStreamUrl(options, basePath, transport)
      return transformUrl?.(url) ?? url
    },
    dedupWindow,
    EventSourceCtor,
    getEventKey,
    getSequence,
    isHeartbeat,
    maxDelayMs,
    onEvent,
    onGap,
    onHealthChange,
    onReconnect,
    parseFrame,
    shouldReconnect,
    sseEvents,
    transport,
    WebSocketCtor,
  })
}
